/*
** EPITECH PROJECT, 2026
** mncc
** File description:
** instructions_form_table
*/

#include "asm/asm.h"

/*  mnemonic, op1, op2, rex_w, prefix, opcode, +reg,
        modrm, reg_field, reg_is_op1, imm, rel32
*/
const instr_form_t instr_table[] = {
    { "mov", OPD_REG, OPD_IMM, true, 0, 0xB8, true,
        false, -1, false, 8, false },
    { "mov", OPD_REG, OPD_REG, true, 0, 0x89, false,
        true, -1, false, 0, false },
    { "mov", OPD_REG, OPD_MEM, true, 0, 0x8B, false,
        true, -1, true, 0, false },
    { "mov", OPD_MEM, OPD_REG, true, 0, 0x89, false,
        true, -1, false, 0, false },
    { "lea", OPD_REG, OPD_MEM, true, 0, 0x8D, false,
        true, -1, true, 0, false },
    { "cmp", OPD_REG, OPD_REG, true, 0, 0x39, false,
        true, -1, false, 0, false },
    { "cmp", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_CMP, false, 1, false },
    { "test", OPD_REG, OPD_REG, true, 0, 0x85, false,
        true, -1, false, 0, false },
    { "test", OPD_REG, OPD_IMM, true, 0, 0xF7, false,
        true, 0, false, 4, false },
    { "sub", OPD_REG, OPD_REG, true, 0, 0x29, false,
        true, -1, false, 0, false },
    { "sub", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_SUB, false, 1, false },
    { "add", OPD_REG, OPD_REG, true, 0, 0x01, false,
        true, -1, false, 0, false },
    { "add", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_ADD, false, 1, false },
    { "and", OPD_REG, OPD_REG, true, 0, 0x21, false,
        true, -1, false, 0, false },
    { "and", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_AND, false, 1, false },
    { "or", OPD_REG, OPD_REG, true, 0, 0x09, false,
        true, -1, false, 0, false },
    { "or", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_OR, false, 1, false },
    { "xor", OPD_REG, OPD_REG, true, 0, 0x31, false,
        true, -1, false, 0, false },
    { "xor", OPD_REG, OPD_IMM, true, 0, 0x83, false,
        true, OPEXT_XOR, false, 1, false },
    { "imul", OPD_REG, OPD_REG, true, 0x0F, 0xAF, false,
        true, -1, true, 0, false },
    /* Groupe F7 : operande unique, extension d'opcode 0-7
    (registres implicites rax/rdx pour mul/div) */
    { "not", OPD_REG, OPD_NONE, true, 0, 0xF7, false,
        true, 2, false, 0, false },
    { "neg", OPD_REG, OPD_NONE, true, 0, 0xF7, false,
        true, 3, false, 0, false },
    { "mul", OPD_REG, OPD_NONE, true, 0, 0xF7, false,
        true, 4, false, 0, false },
    { "div", OPD_REG, OPD_NONE, true, 0, 0xF7, false,
        true, 6, false, 0, false },
    { "idiv", OPD_REG, OPD_NONE, true, 0, 0xF7, false,
        true, 7, false, 0, false },
    /* Groupe FF : inc/dec, operande unique */
    { "inc", OPD_REG, OPD_NONE, true, 0, 0xFF, false,
        true, 0, false, 0, false },
    { "dec", OPD_REG, OPD_NONE, true, 0, 0xFF, false,
        true, 1, false, 0, false },
    /* Decalages/rotations : reg, imm8 -- reutilise
    exactement la forme reg,imm avec opcode C1 */
    { "rol", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 0, false, 1, false },
    { "ror", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 1, false, 1, false },
    { "shl", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 4, false, 1, false },
    { "sal", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 4, false, 1, false },
    { "shr", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 5, false, 1, false },
    { "sar", OPD_REG, OPD_IMM, true, 0, 0xC1, false,
        true, 7, false, 1, false },
    { "push", OPD_REG, OPD_NONE, false, 0, 0x50, true,
        false, -1, false, 0, false },
    { "pop", OPD_REG, OPD_NONE, false, 0, 0x58, true,
        false, -1, false, 0, false },
    { "leave", OPD_NONE, OPD_NONE, false, 0, 0xC9, false,
        false, -1, false, 0, false },
    { "ret", OPD_NONE, OPD_NONE, false, 0, 0xC3, false,
        false, -1, false, 0, false },
    { "syscall", OPD_NONE, OPD_NONE, false, 0x0F, 0x05, false,
        false, -1, false, 0, false },
    { "nop", OPD_NONE, OPD_NONE, false, 0, 0x90, false,
        false, -1, false, 0, false },
    { "cqo", OPD_NONE, OPD_NONE, true, 0, 0x99, false,
        false, -1, false, 0, false },
    { "sete", OPD_REG, OPD_NONE, false, 0x0F, 0x94, false,
        true, 0, false, 0, false },
    { "setne", OPD_REG, OPD_NONE, false, 0x0F, 0x95, false,
        true, 0, false, 0, false },
    { "setg", OPD_REG, OPD_NONE, false, 0x0F, 0x9F, false,
        true, 0, false, 0, false },
    { "setge", OPD_REG, OPD_NONE, false, 0x0F, 0x9D, false,
        true, 0, false, 0, false },
    { "setl", OPD_REG, OPD_NONE, false, 0x0F, 0x9C, false,
        true, 0, false, 0, false },
    { "setle", OPD_REG, OPD_NONE, false, 0x0F, 0x9E, false,
        true, 0, false, 0, false },
    { "seta", OPD_REG, OPD_NONE, false, 0x0F, 0x97, false,
        true, 0, false, 0, false },
    { "setae", OPD_REG, OPD_NONE, false, 0x0F, 0x93, false,
        true, 0, false, 0, false },
    { "setb", OPD_REG, OPD_NONE, false, 0x0F, 0x92, false,
        true, 0, false, 0, false },
    { "setbe", OPD_REG, OPD_NONE, false, 0x0F, 0x96, false,
        true, 0, false, 0, false },
    { "movzx", OPD_REG, OPD_REG, true, 0x0F, 0xB6, false,
        true, -1, true, 0, false },
    { "movsx", OPD_REG, OPD_REG, true, 0x0F, 0xBE, false,
        true, -1, true, 0, false },
    { "jmp", OPD_LABEL, OPD_NONE, false, 0, 0xE9, false,
        false, -1, false, 4, true },
    { "call", OPD_LABEL, OPD_NONE, false, 0, 0xE8, false,
        false, -1, false, 4, true },
    { "je", OPD_LABEL, OPD_NONE, false, 0x0F, 0x84, false,
        false, -1, false, 4, true },
    { "jne", OPD_LABEL, OPD_NONE, false, 0x0F, 0x85, false,
        false, -1, false, 4, true },
    { "jg", OPD_LABEL, OPD_NONE, false, 0x0F, 0x8F, false,
        false, -1, false, 4, true },
    { "jge", OPD_LABEL, OPD_NONE, false, 0x0F, 0x8D, false,
        false, -1, false, 4, true },
    { "jl", OPD_LABEL, OPD_NONE, false, 0x0F, 0x8C, false,
        false, -1, false, 4, true },
    { "jle", OPD_LABEL, OPD_NONE, false, 0x0F, 0x8E, false,
        false, -1, false, 4, true },
    { "ja", OPD_LABEL, OPD_NONE, false, 0x0F, 0x87, false,
        false, -1, false, 4, true },
    { "jae", OPD_LABEL, OPD_NONE, false, 0x0F, 0x83, false,
        false, -1, false, 4, true },
    { "jb", OPD_LABEL, OPD_NONE, false, 0x0F, 0x82, false,
        false, -1, false, 4, true },
    { "jbe", OPD_LABEL, OPD_NONE, false, 0x0F, 0x86, false,
        false, -1, false, 4, true },
};

const size_t instr_table_len = sizeof(instr_table) / sizeof(instr_table[0]);
