/*
** EPITECH PROJECT, 2026
** mncc
** File description:
** codegen.c - Top-level code generation for the MNC compiler
*/

#include "mncc.h"

int collect_locals(node_t *block, char **locals, int count)
{
    int i = 0;

    if (!block || block->type != NODE_BLOCK)
        return count;
    while (i < block->child_count) {
        if (block->children[i]->type == NODE_DECL) {
            locals[count] = block->children[i]->name;
            count++;
        }
        i++;
    }
    return count;
}

int find_local(codegen_ctx_t *ctx, char *name)
{
    int i = 0;

    while (i < ctx->local_count) {
        if (strcmp(ctx->locals[i], name) == 0)
            return (i + 1) * 8;
        i++;
    }
    return 0;
}

void gen_func(node_t *node, codegen_ctx_t *ctx)
{
    int i = 0;
    char *regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};

    ctx->locals = xmalloc(sizeof(char *) * 64);
    ctx->local_count = 0;
    ctx->func_name = node->name;
    while (i < node->child_count) {
        ctx->locals[ctx->local_count++] = node->children[i]->name;
        i++;
    }
    ctx->local_count = collect_locals(node->body, ctx->locals,
        ctx->local_count);
    fprintf(ctx->out, "%s:\n", node->name);
    fprintf(ctx->out, "    push rbp\n");
    fprintf(ctx->out, "    mov rbp, rsp\n");
    fprintf(ctx->out, "    sub rsp, %d\n", ctx->local_count * 8);
    i = 0;
    while (i < node->child_count && i < 6) {
        fprintf(ctx->out, "    mov [rbp - %d], %s\n",
            (i + 1) * 8, regs[i]);
        i++;
    }
    gen_block(node->body, ctx);
    fprintf(ctx->out, ".%s_end:\n", node->name);
    fprintf(ctx->out, "    mov rsp, rbp\n");
    fprintf(ctx->out, "    pop rbp\n");
    fprintf(ctx->out, "    ret\n\n");
    free(ctx->locals);
    ctx->locals = NULL;
    ctx->func_name = NULL;
}

void codegen(node_t *ast, FILE *out)
{
    codegen_ctx_t ctx;
    int i = 0;

    ctx.locals = NULL;
    ctx.local_count = 0;
    ctx.label_count = 0;
    ctx.out = out;
    ctx.func_name = NULL;
    fprintf(out, "; Generated by MNC\n");
    fprintf(out, "section .text\n");
    fprintf(out, "global _start\n\n");
    fprintf(out, "_start:\n");
    fprintf(out, "    call main\n");
    fprintf(out, "    mov rdi, rax\n");
    fprintf(out, "    mov rax, 60\n");
    fprintf(out, "    syscall\n\n");
    while (i < ast->child_count) {
        gen_func(ast->children[i], &ctx);
        i++;
    }
}
