name: Build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Check commit message for ci-skip
      id: check
      run: |
        if git log -1 --pretty=%B | grep -q "*ci-skip*"; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

  basic-build:
    needs: check-skip
    runs-on: ubuntu-latest
    if: "needs.check-skip.outputs.skip != 'true'"

    steps:
    - uses: actions/checkout@v6
    - name: make
      run: make CICD=1
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make CICD=1 re
    - name: check binary
      run: ls -l ./mncc
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  cs-build:
    needs: [check-skip, basic-build]
    runs-on: ubuntu-latest
    if: "needs.check-skip.outputs.skip != 'true'"

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile ./Dockerfile
    - name: Build coding-style tests
      run: docker build . -t cs-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run cs-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
  
  coverage-build:
    needs: [check-skip, basic-build]
    runs-on: ubuntu-latest
    if: "needs.check-skip.outputs.skip != 'true'"

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile2 ./Dockerfile
    - name: Build coverage-style tests
      run: docker build . -t coverage-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run coverage-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  valgrind-build:
    needs: [check-skip, basic-build]
    runs-on: ubuntu-latest
    if: "needs.check-skip.outputs.skip != 'true'"
    
    steps:
    - uses: actions/checkout@v6
    - name: update apt
      run : sudo apt-get update
    - name: setup valgrind
      run:  sudo apt-get install -y valgrind
    - name: make
      run: make CICD=1 DEBUG=1
    - name: check file
      run: ls -l ./mncc
    - name: run valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all ./mncc ./main.c
    - name: clean
      run: make fclean
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  scan-build-test:
    needs: [check-skip, basic-build]
    runs-on: ubuntu-latest
    if: "needs.check-skip.outputs.skip != 'true'"

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile3 ./Dockerfile
    - name: Build scan-build tests
      run: docker build . -t cs-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run scan-build tests
      run : docker run cs-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}