name: Build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  basic-build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
    - uses: actions/checkout@v6
    - name: make
      run: make CICD=1
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make CICD=1 re
    - name: check binary
      run: ls -l ./mncc
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  cs-build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile ./Dockerfile
    - name: Build coding-style tests
      run: docker build . -t cs-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run cs-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
  
  coverage-build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile2 ./Dockerfile
    - name: Build coverage-style tests
      run: docker build . -t coverage-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run coverage-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  valgrind-build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    
    steps:
    - uses: actions/checkout@v6
    - name: update apt
      run : sudo apt-get update
    - name: setup valgrind
      run:  sudo apt-get install -y valgrind
    - name: make
      run: make CICD=1 DEBUG=1
    - name: check file
      run: ls -l ./mncc
    - name: run valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all ./mncc ./main.c
    - name: clean
      run: make fclean
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}